tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: TASTY_BYTES_DBT_HORIE_DB
      schema: dev
      warehouse: HORIE_WH_XL
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: TASTY_BYTES_DBT_HORIE_DB
      schema: prod
      warehouse: HORIE_WH_XL